version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 10
    reviewers:
      - "ahmetcemkaraca"
    assignees:
      - "ahmetcemkaraca"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      # Ignore major React updates (manual review needed)
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "Europe/Istanbul"
    open-pull-requests-limit: 5
    reviewers:
      - "ahmetcemkaraca"
    assignees:
      - "ahmetcemkaraca"
    commit-message:
      prefix: "🔧"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"