name: 🐛 Bug Report
description: Create a report to help us improve ArchBuilder.AI Website
title: "🐛 [Bug]: "
labels: ["bug", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        
        **For Copilot users**: Please review the `.github/copilot-instructions.md` and relevant instruction files before implementation.

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component or area is affected?
      options:
        - UI Components (Hero, Features, CTA, etc.)
        - i18n/Translation System
        - Navigation/Layout
        - Forms/User Input
        - Performance/Analytics
        - Build/Deployment
        - Other
    validations:
      required: true

  - type: checkboxes
    id: development-checklist
    attributes:
      label: Development Checklist (for Copilot implementers)
      options:
        - label: I have read the relevant `.github/instructions/*.instructions.md` files
        - label: I understand the Next.js 15 + TypeScript + i18n architecture
        - label: I will follow the git branch workflow (feature branches)
        - label: I will update registry files if adding/modifying components