name: CI/CD Pipeline - Optimized

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]

env:
  NODE_VERSION: '20'

jobs:
  # Tek build job - maliyet optimizasyonu
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript check
      run: npx tsc --noEmit

    - name: Run tests (if exist)
      run: |
        if [ -f "src/__tests__/hero.test.tsx" ]; then
          npm test -- --coverage --watchAll=false
        else
          echo "No tests found, skipping..."
        fi

    - name: Build project
      run: npm run build

    - name: Validate static export
      run: |
        test -f out/index.html || exit 1
        test -d out/_next/static || exit 1
        echo "✅ Static export validation successful!"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main'
      with:
        name: website-build
        path: out/
        retention-days: 3

  # Sadece production branch için güvenlik kontrolü
  security-audit:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Security audit
      run: npm audit --audit-level=high

  # Sadece production deployment (maliyet optimizasyonu)
  deploy-production:
    runs-on: ubuntu-latest
    needs: [build-and-test, security-audit]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: website-build
        path: out/
    - name: Deploy notification
      run: echo "🚀 Production deployment ready for manual trigger"

