name: CI/CD Pipeline - Optimized

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main, develop ]



jobs:
  # Tek build job - maliyet optimizasyonu
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5


      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci --legacy-peer-deps

    - name: Run ESLint
      run: npm run lint

    - name: Run TypeScript check
      run: npx tsc --noEmit

    - name: Run tests (if exist)
      run: |
        if [ -f "src/__tests__/hero.test.tsx" ]; then
          npm test -- --coverage --watchAll=false
        else
          echo "No tests found, skipping..."
        fi

    - name: Build project
      run: npm run build

    - name: Validate static export
      run: |
        test -f out/index.html || exit 1
        test -d out/_next/static || exit 1
        echo "✅ Static export validation successful!"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4

      with:
        name: website-build
        path: out/
        retention-days: 3
      with:
        name: website-build
        path: out/
    - name: Deploy notification
      run: echo "🚀 Production deployment ready for manual trigger"

