name: Quick Lint Check
on:
  pull_request:
    paths:
      - 'src/**'
      - '*.js'
      - '*.ts'
      - '*.json'
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - '*.js'
      - '*.ts'
      - '*.json'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci --legacy-peer-deps
      - run: npm run lint
